### PR TITLE
Apollo fragment types

### PR DESCRIPTION
**Pull request by ZauberNerd**
In case an apollo cache is passed via render options, it was previously
not possible to pass `possibleTypes` (aka fragmentTypes.json`) to the
cache constructor, because the file was only read in the server mixin.

With this change the fragmentTypes.json file is available via a webpack
alias as `hops-react-apollo/fragmentTypes.json`, so users can import
that file from their application code and pass it to the cache via
render options.

Additionally this change contains a fix for the cache restoration on
the client-side when a custom cache was passed via render options,
which would previously not result in the SSR cache state being restored.

<details>
<summary>Bors merge bot cheat sheet</summary>

We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a summary of commands that are available to reviewers (members of this repository with push access) and delegates (in case of `bors delegate+` or `bors delegate=[list]`).

| Syntax | Description |
| --- | --- |
| bors merge | Run the test suite and push to master if it passes. Short for "reviewed: looks good." |
| bors merge- | Cancel an r+, r=, merge, or merge= |
| bors try | Run the test suite without pushing to master. |
| bors try- | Cancel a try |
| bors delegate+ | Allow the pull request author to merge their changes. |
| bors delegate=[list] | Allow the listed users to r+ this pull request's changes. |
| bors retry | Run the previous command a second time. |

This is a short collection of opinionated commands. For a full list of the commands read the [bors reference](https://bors.tech/documentation/).

</details>

### CODE REVIEW

**Review by Poltergeist — APPROVED** [review]

**Comment by ZauberNerd** [comment]
bors merge

**Comment by ZauberNerd** [comment]
bors merge-

**Comment by ZauberNerd** [comment]
bors retry

**Comment by ZauberNerd** [comment]
bors merge

**Comment by ZauberNerd** [comment]
bors merge

**Comment by ZauberNerd** [comment]
bors merge

**Pull request merged**
