### PR TITLE
remove deprecated apollo

### PR DESCRIPTION
**Pull request by robertkowalski**
## Current state
apollo client 2 was deprecated and due to removal in hops 15

## Changes introduced here

removes the deprecated apollo client 2 for hops 15

## Checklist

- [x] All commit messages adhere to the [appropriate format](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit) in order to trigger a correct release
- [x] All code is written in untranspiled ECMAScript (ES 2017) and is formatted using [prettier](https://prettier.io)

<details>
<summary>Bors merge bot cheat sheet</summary>

We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a summary of commands that are available to reviewers (members of this repository with push access) and delegates (in case of `bors delegate+` or `bors delegate=[list]`).

| Syntax | Description |
| --- | --- |
| bors merge | Run the test suite and push to master if it passes. Short for "reviewed: looks good." |
| bors merge- | Cancel an r+, r=, merge, or merge= |
| bors try | Run the test suite without pushing to master. |
| bors try- | Cancel a try |
| bors delegate+ | Allow the pull request author to merge their changes. |
| bors delegate=[list] | Allow the listed users to r+ this pull request's changes. |
| bors retry | Run the previous command a second time. |

This is a short collection of opinionated commands. For a full list of the commands read the [bors reference](https://bors.tech/documentation/).

</details>

### CODE REVIEW

**Comment by ZauberNerd** [comment]
Please remove the `apollo3` folder and move the mixins into the `packages/react-apollo/mixins/` folder.

**Review by ZauberNerd — CHANGES_REQUESTED** [review]
Please follow semantic commits and annotate this commit correctly as a breaking change: https://www.conventionalcommits.org/en/v1.0.0/#summary

**Review by jhiode — APPROVED** [review]
:tada:

**Comment by robertkowalski** [comment]
bors merge

**Comment by robertkowalski** [comment]
bors merge

**Comment by robertkowalski** [comment]
seems bors broken, had similar issue with https://github.com/xing/hops/pull/1962 - lets fix it after the hops release

**Pull request merged**
