### PR TITLE
Replaces de current logo with a XINGier one

### PR DESCRIPTION
**Pull request by rudeworks**

### CODE REVIEW

**Comment by dmbch** [comment]
Thank you! I'd love to merge it, but I currently can't: Your branch is not in sync with master... 
@rudeworks Could you update it and push again, please?

**Comment by dmbch** [comment]
Oh, and could you update/remove the last lines of our readme.md, too?

**Comment by rcsole** [comment]
@rudeworks you should add yourself to the contributors list too!

https://github.com/xing/hops/blob/master/package.json#L33-L36

**Comment by rudeworks** [comment]
@dmbch should be ok to merge now ;)

**Pull request merged**
