### PR TITLE
Context cloning

### PR DESCRIPTION
**Pull request by dmbch**
## Current state

Currently, cloned context mixins have to take care of merging options.

## Changes introduced here

With the proposed change, context mixin constructors receive a single merged options hash.

## Checklist

* [X] All commit messages adhere to the [appropriate format](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit) in order to trigger a correct release
* [X] All code is written in plain ECMAScript v5 and is formatted using [prettier](https://prettier.io)
* [ ] Necessary unit tests are added in order to ensure correct behavior
* [ ] Documentation has been added

### CODE REVIEW

**Comment by robin-drexler** [comment]
That'd be a breaking change, wouldn't it?

**Comment by dmbch** [comment]
@robin-drexler technically yes, realistically probably not, as it is only altering an undocumented and thus private-ish API.

**Comment by dmbch** [comment]
@KingHenne what do you think? Important improvement or just cosmetics?

**Comment by KingHenne** [comment]
@dmbch To be honest I don't quite understand how `mixinable.replicate` works. But it seems this change means the options are passed to the context already merged so I don't have to merge them in my constructor? In this case I think it's a valuable improvement and not only "cosmetics".

**Comment by KingHenne** [comment]
Alright, after reading the [test](https://github.com/dmbch/mixinable/blob/41c7e8dcea3613dc38bb8eb8f6e4155b9b577a53/test.js#L469-L488) I get it now. Looks good then! ... Although I find this meta-programming with `mixinable` quite hard to understand. 😕

**Comment by dmbch** [comment]
@KingHenne thanks for your input! 

To be honest, I'd love to replace `mixininable` with something more straightforward, but I don't currently have an idea what existing lib or framework we might be using here. We need/want composition capabilities on the one hand and isolation on the other. 

Pseudo-classical inheritance (`class extends Foo {}`, `Foo.extend()`) does not really work for us, because we need to able to mix, modify and match context implementations: we need to be able to support all possible combinations of `React`, `Redux`, `GraphQL`, `I18n` and custom contexts...

So if you have a simpler idea that would be massively appreciated!

**Pull request merged**
