### PR TITLE
Prepare next Hops 13.x release

### PR DESCRIPTION
**Pull request by ZauberNerd**
Next release: Monday, November 30th

* [Fix babel transpilation target (always transpile new syntax) (#1439)](https://github.com/xing/hops/pull/1439)
* [fix(bootstrap): do not try to resolve ESM packages for presets (#1438)](https://github.com/xing/hops/pull/1438)

<details>
<summary>Bors merge bot cheat sheet</summary>

We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a summary of commands that are available to reviewers (members of this repository with push access) and delegates (in case of `bors delegate+` or `bors delegate=[list]`).

| Syntax | Description |
| --- | --- |
| bors merge | Run the test suite and push to master if it passes. Short for "reviewed: looks good." |
| bors merge- | Cancel an r+, r=, merge, or merge= |
| bors try | Run the test suite without pushing to master. |
| bors try- | Cancel a try |
| bors delegate+ | Allow the pull request author to merge their changes. |
| bors delegate=[list] | Allow the listed users to r+ this pull request's changes. |
| bors retry | Run the previous command a second time. |

This is a short collection of opinionated commands. For a full list of the commands read the [bors reference](https://bors.tech/documentation/).

</details>

### CODE REVIEW

**Comment by herschel666** [comment]
*FYI*: removed #1427 & #1432 here and cherry-picked onto `v13.x`, because they were needed immediately and they weren't relevant for the release.

Did we already consider those types of commits with regards to the release bot?

**Review by jhiode — APPROVED** [review]

**Comment by ZauberNerd** [comment]
bors merge

**Comment by ZauberNerd** [comment]
bors merge

**Comment by ZauberNerd** [comment]
bors merge

**Pull request merged**
