### PR TITLE
Prepare next v11 release

### PR DESCRIPTION
**Pull request by ZauberNerd**
<details>
<summary>Bors merge bot cheat sheet</summary>

We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a summary of commands that are available to reviewers (members of this repository with push access) and delegates (in case of `bors delegate+` or `bors delegate=[list]`).

| Syntax | Description |
| --- | --- |
| bors merge | Run the test suite and push to master if it passes. Short for "reviewed: looks good." |
| bors merge- | Cancel an r+, r=, merge, or merge= |
| bors try | Run the test suite without pushing to master. |
| bors try- | Cancel a try |
| bors delegate+ | Allow the pull request author to merge their changes. |
| bors delegate=[list] | Allow the listed users to r+ this pull request's changes. |
| bors retry | Run the previous command a second time. |

This is a short collection of opinionated commands. For a full list of the commands read the [bors reference](https://bors.tech/documentation/).

</details>

### CODE REVIEW

**Comment by ZauberNerd** [comment]
@herschel666 @jhiode @KnisterPeter when adding an approving review you can just comment `bors merge` on it and bors will automatically take care of running all tests against a master merge and then merge this PR into the v11.x branch :)

**Comment by ZauberNerd** [comment]
bors retry

**Comment by ZauberNerd** [comment]
Looks like a fluke in our internal CI. Let's try again...

bors retry

**Comment by ZauberNerd** [comment]
bors merge

**Comment by ZauberNerd** [comment]
bors ping

**Comment by ZauberNerd** [comment]
bors merge

**Comment by ZauberNerd** [comment]
bors merge

**Comment by ZauberNerd** [comment]
bors retry

**Comment by ZauberNerd** [comment]
bors retry

**Comment by ZauberNerd** [comment]
bors retry

**Comment by KnisterPeter** [comment]
bors retry

**Pull request merged**
