### PR TITLE
Prettier

### PR DESCRIPTION
**Pull request by dmbch**
## Current state

Hops does not use [prettier](https://prettier.io).

## Changes introduced here

It now does.

## Checklist

- [X] All commit messages adhere to the [appropriate format](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit) in order to trigger a correct release
- [X] All code is written in plain ECMAScript v5 and is formatted using [prettier](https://prettier.io).
- [ ] Necessary unit tests are added in order to ensure correct behavior
- [X] Documentation has been added

### CODE REVIEW

**Comment by robin-drexler** [comment]
What does "It now does." mean exactly? Where is it supposed to invoke prettier automatically?
I assumed it's now a precommit hook, but that didn't work (at first try). :D

**Comment by dmbch** [comment]
@robin-drexler that is a bit weird: for me, it does work as a precommit hook. Would you mind `yarn reset`ing your clone and trying once more?

Other than that, I added a package script allowing us to `yarn fmt` the whole project.

**Comment by robin-drexler** [comment]
After a fresh clone the precommit hook works fine. 👍 
However, running `yarn` resulted in a changed `yarn.lock`. Did you forget to check it in?

**Comment by dmbch** [comment]
@robin-drexler no, but I think I `prettier`ed it, too...

**Pull request merged**
