### PR TITLE
feat(express): enable gzip compression

### PR DESCRIPTION
**Pull request by ZauberNerd**
This PR adds gzip compression to the express server.

~WIP because it needs investigation how Lambda / API Gateway behave when
they deal with gzip compressed responses.~
API Gateway expects Lambda to return compressed responses in order to serve compressed responses to the client.

### CODE REVIEW

**Comment by robin-drexler** [comment]
💯🔥

**Comment by ZauberNerd** [comment]
Lambda / API Gateway does not do compression on their own, but will handle gzip compressed responses properly when the Lambda function returns a gzipped response.
Therefore I think we should implement this. If there really is concern about performance in other scenarios we could think about enabling compression only when NODE_ENV is set to "production" or even rely on other environment variables that are only set on AWS Lambda.

**Comment by ZauberNerd** [comment]
@dmbch we could for example check if the `LAMBDA_TASK_ROOT` is set, which should only happen on AWS Lambda, so that Hops running behind a reverse proxy will still serve uncompressed content and leave the compression to the proxy: https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html#lambda-environment-variables

**Comment by dmbch** [comment]
@zaubernerd interesting idea. Although we could also merge this feature as-is and iterate..?

N.B.: yeah, we changed my mind. And we must make this stuff less monolithic :grin:

**Pull request merged**
