### PR TITLE
fix(webpack): accept object argument in BuildError (v12.x)

### PR DESCRIPTION
**Pull request by jhiode**
Picking #1380

### CODE REVIEW

**Review by herschel666 — DISMISSED** [review]

**Comment by jhiode** [comment]
bors merge

**Comment by jhiode** [comment]
bors merge

**Comment by jhiode** [comment]
bors merge

**Review by herschel666 — APPROVED** [review]

**Comment by herschel666** [comment]
bors merge

**Comment by herschel666** [comment]
bors merge-

**Pull request merged**
