### PR TITLE
chore(hops): prefix stdout consistently with name

### PR DESCRIPTION
**Pull request by herschel666**
Before:
before

After:
after

### CODE REVIEW

**Comment by robin-drexler** [comment]
Not sure I like that. If the package name something is `@myscope/my-package-name`, loads of screen real estate is wasted imo. How about making it consistent by removing it entirely? Is there even any value in having it at all?

**Comment by herschel666** [comment]
I would argue, that Terminal screen estate isn't a scarce resource. And of course devs want to have feedback on what Hops is about to do.

There's one thing though with long project names: the readability might suffer. But I actually don't expect this to be the case.

**Comment by robin-drexler** [comment]
It's also tedious to parse the cli output, because not all output has the prefix. I don't think we can ensure every log line will have it, can we?

**Comment by jhiode** [comment]
As the other log line already includes the name I think it is a good idea to do the same for all (or the other log lines that you see all the time).

**Comment by robin-drexler** [comment]
@jhiode  Can you give some reasoning why you think having the prefix is useful at all?

> As the other log line already includes the name
Isn't a value in itself imo, as consistency could also be achieved by removing the prefix there as well.

**Comment by ZauberNerd** [comment]
Let's close this for now until we have a more comprehensive solution in untool and re-use that then.

**Pull request closed without merging**
