### PR TITLE
Fix lambda diagnosis hook (v12.x)

### PR DESCRIPTION
**Pull request by herschel666**
picks #1354 

<details>
<summary>Bors merge bot cheat sheet</summary>

We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a summary of commands that are available to reviewers (members of this repository with push access) and delegates (in case of `bors delegate+` or `bors delegate=[list]`).

| Syntax | Description |
| --- | --- |
| bors merge | Run the test suite and push to master if it passes. Short for "reviewed: looks good." |
| bors merge- | Cancel an r+, r=, merge, or merge= |
| bors try | Run the test suite without pushing to master. |
| bors try- | Cancel a try |
| bors delegate+ | Allow the pull request author to merge their changes. |
| bors delegate=[list] | Allow the listed users to r+ this pull request's changes. |
| bors retry | Run the previous command a second time. |

This is a short collection of opinionated commands. For a full list of the commands read the [bors reference](https://bors.tech/documentation/).

</details>

### CODE REVIEW

**Review by ZauberNerd — APPROVED** [review]

**Comment by herschel666** [comment]
bors merge

**Comment by herschel666** [comment]
bors retry

**Comment by herschel666** [comment]
bors retry

**Comment by herschel666** [comment]
The test that checks `create-react-app` with Yarn fails, because the demanded `latest` version of Hops (13) is incompatible with the Node version range of the base branch of this PR:

```
error hops@13.0.0: The engine "node" is incompatible with this module. Expected version "12 || 14". Got "10.20.1"
error Found incompatible module.
```

We could either `--ignore-engines` or come up with a more sophisticated approach. WDYT?

**Comment by herschel666** [comment]
Given the troubles with regards to the mismatching required Node versions & the fact, that this fix has been released with Hops 13: is this PR worth the effort? Or do we rather want to close it?

**Comment by ZauberNerd** [comment]
bors merge

**Comment by ZauberNerd** [comment]
> Given the troubles with regards to the mismatching required Node versions & the fact, that this fix has been released with Hops 13: is this PR worth the effort? Or do we rather want to close it?

Let's close it.

**Pull request closed without merging**
