### PR TITLE
chore: ci - remove node 12

### PR DESCRIPTION
**Pull request by robertkowalski**
## Changes introduced here

Remove 12.x from the github actions as hops 15 does not support node 12 any more.

## Checklist

- [x] All commit messages adhere to the [appropriate format](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit) in order to trigger a correct release

<details>
<summary>Bors merge bot cheat sheet</summary>

We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a summary of commands that are available to reviewers (members of this repository with push access) and delegates (in case of `bors delegate+` or `bors delegate=[list]`).

| Syntax | Description |
| --- | --- |
| bors merge | Run the test suite and push to master if it passes. Short for "reviewed: looks good." |
| bors merge- | Cancel an r+, r=, merge, or merge= |
| bors try | Run the test suite without pushing to master. |
| bors try- | Cancel a try |
| bors delegate+ | Allow the pull request author to merge their changes. |
| bors delegate=[list] | Allow the listed users to r+ this pull request's changes. |
| bors retry | Run the previous command a second time. |

This is a short collection of opinionated commands. For a full list of the commands read the [bors reference](https://bors.tech/documentation/).

</details>

### CODE REVIEW

**Comment by ZauberNerd** [comment]
We should also update the `engines` fields in the package.json files.

**Comment by ZauberNerd** [comment]
Should we remove v15 too and replace it with v17 (which will come out in October)?
https://nodejs.org/en/about/releases/
We usually only support one non-lts release and since the next lts release (v16) is already there and v17 will be available soon after the release, I was thinking maybe it is time to drop v15 too.
WDYT?

**Comment by jhiode** [comment]
I agree on dropping Node v15 as it's not even listed anymore on the releases page. But we should probably wait with adding v17 until it's released and we've tested it with Hops.

**Review by ZauberNerd — CHANGES_REQUESTED** [review]
Please follow semantic commits and annotate this commit correctly as a breaking change: https://www.conventionalcommits.org/en/v1.0.0/#summary

**Review by ZauberNerd — APPROVED** [review]
bors merge

**Comment by robertkowalski** [comment]
bors retry

**Comment by robertkowalski** [comment]
bors retry

**Comment by robertkowalski** [comment]
bors merge-

**Comment by robertkowalski** [comment]
bors merge

**Comment by robertkowalski** [comment]
bors merge-

**Comment by robertkowalski** [comment]
bors merge

**Comment by ZauberNerd** [comment]
bors merge

**Comment by robertkowalski** [comment]
bors merge

**Comment by robertkowalski** [comment]
bors retry

**Comment by robertkowalski** [comment]
bors retry

**Comment by robertkowalski** [comment]
bors retry

**Comment by robertkowalski** [comment]
bors merge is green, bot hangs

**Pull request merged**
