### PR TITLE
chore(spec): improve programmatic HopsCLI

### PR DESCRIPTION
**Pull request by herschel666**
First draft of the improved `HopsCLI`. As soon as we'll have agreed upon the API, this should either be refactored out of `packages/spec` into its own released package. Or `packages/spec` needs to be released (without all the tests obviously…).

<details>
<summary>Bors merge bot cheat sheet</summary>

We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a summary of commands that are available to reviewers (members of this repository with push access) and delegates (in case of `bors delegate+` or `bors delegate=[list]`).

| Syntax | Description |
| --- | --- |
| bors merge | Run the test suite and push to master if it passes. Short for "reviewed: looks good." |
| bors merge- | Cancel an r+, r=, merge, or merge= |
| bors try | Run the test suite without pushing to master. |
| bors try- | Cancel a try |
| bors delegate+ | Allow the pull request author to merge their changes. |
| bors delegate=[list] | Allow the listed users to r+ this pull request's changes. |
| bors retry | Run the previous command a second time. |

This is a short collection of opinionated commands. For a full list of the commands read the [bors reference](https://bors.tech/documentation/).

</details>

### CODE REVIEW

**Comment by herschel666** [comment]
currently blocked by #1480

**Review by ZauberNerd — CHANGES_REQUESTED** [review]
I liked how you commented and typed the new API :+1: 
But other than that, I'm not really happy with it. It's usage seems more complicated than before:
- cwd is always required and before we were able to use it directly from the Jest environment, while now we have to pass it in explicitly every time
- the builder pattern is overly complicated and does not add value in this case
Overall, this feels a bit over-engineered to me and I'd prefer to go back to something simpler :smile:

**Comment by herschel666** [comment]
I agree with you concerning the `cwd`-value & I switched back to using the global one.

Regarding your concern, that it's overly complicated, I wonder when was the last time you've worked with `HopsCLI`? Have you seen in the red part of this PR's diff, how complicated it became, to put in env vars and CLI-flags? And how cumbersome it became to get `stderr` and `stdout` out of it? The new `HopsCLI` has straight-forward APIs for all of that.

So I guess we need more opinions here. 🤷‍♂️

**Comment by KnisterPeter** [comment]
I do not have a strong opinion here, since I've never used the HopsCLI tool, but I would question the builder-style API here.
I think its not very easy to use.
My biggest problem here is mostly: I don't know/understand why we need to change this. Is it internal only? Who needs access to this? What are the limiting factors in the current implementation.

**Comment by herschel666** [comment]
So `HopsCLI` used to be a fire-and-forget tool — run a command & don't care about it. But lately the requirements have been introduced, to set env variables and to retrieve the `stderr` of the process.

This is where things got messy — under the hood as well as in the public API.

Hence the overhaul. And since there's some kind of state involved, I decided to go with a `class`. Maybe I got carried away a little regarding the API design…

I will see whether I can come up with a less _classy_ approach.

**Comment by herschel666** [comment]
Sh*t, forgot to delete the obsolete helper functions. 😖 Now the diff is complete.

**Comment by herschel666** [comment]
superseded by #1481

**Pull request closed without merging**
